// SPDX-License-Identifier: Apache-2.0 OR MIT
// port-lint: source src/lib.rs
package io.github.kotlinmania.lalrpoputil

/**
 * Error type for errors returned by lalrpop parsers.
 *
 * For the built-in lexer, the generic parameters default to:
 * `ParseError<Int, lexer.Token, String>`.
 *
 * - `L`: the location of the Token where the error occurred.
 * - `T`: the token encountered where the error occurred.
 * - `E`: a custom user-defined error.
 *
 * `L` and `T` are fixed types as listed above for built in lexers, and can be
 * defined to whatever type you would like if implementing a custom lexer.
 *
 * The type of `E` can be overridden by specifying `type Error` in your grammar.
 */
sealed class ParseError<L, T, E> {
    /**
     * Generated by the internal lexer when it encounters a token (or EOF) it
     * did not expect.
     */
    data class InvalidToken<L, T, E>(
        /** The end of the invalid token. */
        val location: L,
    ) : ParseError<L, T, E>()

    /** Generated by the parser when it encounters an EOF it did not expect. */
    data class UnrecognizedEof<L, T, E>(
        /** The end of the final token. */
        val location: L,
        /**
         * The set of expected tokens: these names are taken from the grammar
         * and hence may not necessarily be suitable for presenting to the user.
         */
        val expected: List<String>,
    ) : ParseError<L, T, E>()

    /**
     * Generated by the parser when it encounters a token it did not expect.
     *
     * This means that the next token in the stream was not valid at this point
     * in the grammar.
     */
    data class UnrecognizedToken<L, T, E>(
        /** The unexpected token of type `T` with a span given by the two `L` values. */
        val token: Triple<L, T, L>,
        /**
         * The set of expected tokens: these names are taken from the grammar
         * and hence may not necessarily be suitable for presenting to the user.
         */
        val expected: List<String>,
    ) : ParseError<L, T, E>()

    /** Generated by the parser when it encounters additional, unexpected tokens. */
    data class ExtraToken<L, T, E>(
        /** The extra token, with a type of `T` with a span given by the two `L` values. */
        val token: Triple<L, T, L>,
    ) : ParseError<L, T, E>()

    /** Custom error type. */
    data class User<L, T, E>(
        /** Custom user error. */
        val error: E,
    ) : ParseError<L, T, E>()

    final override fun toString(): String = fmt()

    private fun fmt(): String = when (this) {
        is User -> error.toString()
        is InvalidToken -> "Invalid token at $location"
        is UnrecognizedEof -> StringBuilder("Unrecognized EOF found at $location")
            .also { fmtExpected(it, expected) }
            .toString()
        is UnrecognizedToken -> {
            val (start, tok, end) = token
            StringBuilder("Unrecognized token `$tok` found at $start:$end")
                .also { fmtExpected(it, expected) }
                .toString()
        }
        is ExtraToken -> {
            val (start, tok, end) = token
            "Extra token $tok found at $start:$end"
        }
    }

    private fun <LL, TT, EE> mapIntern(
        locOp: (L) -> LL,
        tokOp: (T) -> TT,
        errOp: (E) -> EE,
    ): ParseError<LL, TT, EE> {
        // The signature of `token` is `(L, T, L)`, so we need to call `locOp`
        // on both the "start" and "end" values for a token.
        val mapTok: (Triple<L, T, L>) -> Triple<LL, TT, LL> =
            { (s, t, e) -> Triple(locOp(s), tokOp(t), locOp(e)) }
        return when (this) {
            is InvalidToken -> InvalidToken(locOp(location))
            is UnrecognizedEof -> UnrecognizedEof(locOp(location), expected)
            is UnrecognizedToken -> UnrecognizedToken(mapTok(token), expected)
            is ExtraToken -> ExtraToken(mapTok(token))
            is User -> User(errOp(error))
        }
    }

    /**
     * Transform a `ParseError` by applying a function to the location field.
     *
     * This could be useful to ensure that all fields implement some trait, or
     * to apply an offset to a location.
     *
     * (Note that unlike [mapToken] and [mapError], the closure argument for
     * this function may be called multiple times, to apply to the starting and
     * ending location of tokens.)
     */
    fun <LL> mapLocation(op: (L) -> LL): ParseError<LL, T, E> =
        mapIntern(op, { it }, { it })

    /**
     * Transform a `ParseError` by applying a function to the token field.
     *
     * This could be useful to ensure that all fields implement some trait, or
     * to transform a token in some way (eg escaping).
     */
    fun <TT> mapToken(op: (T) -> TT): ParseError<L, TT, E> =
        mapIntern({ it }, op, { it })

    /**
     * Transform a `ParseError` by applying a function to the error field.
     *
     * This could be useful to ensure that all fields implement some trait, or
     * to transform to a different error type in place.
     */
    fun <EE> mapError(op: (E) -> EE): ParseError<L, T, EE> =
        mapIntern({ it }, { it }, op)

    /**
     * The static description string upstream returns from
     * `core::error::Error::description`. The upstream method is deprecated;
     * the description is kept here as a parity-preserving property.
     */
    val description: String
        get() = "parse error"

    companion object {
        /** Wraps a custom error into a [ParseError.User]. */
        fun <L, T, E> from(error: E): ParseError<L, T, E> = User(error)
    }
}

/**
 * Format a list of expected tokens onto [sb] using the same comma-and-or
 * scheme upstream uses (`Expected one of A, B or C`).
 */
private fun fmtExpected(sb: StringBuilder, expected: List<String>) {
    if (expected.isNotEmpty()) {
        sb.append('\n')
        for ((i, e) in expected.withIndex()) {
            val sep = when {
                i == 0 -> "Expected one of"
                i < expected.size - 1 -> ","
                // Last expected message to be written.
                else -> " or"
            }
            sb.append("$sep $e")
        }
    }
}
