// SPDX-License-Identifier: Apache-2.0 OR MIT

import com.vanniktech.maven.publish.SonatypeHost
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    kotlin("multiplatform") version "2.3.20"
    id("com.android.kotlin.multiplatform.library") version "9.2.0"
    id("com.vanniktech.maven.publish") version "0.30.0"
}

group = "io.github.kotlinmania"
version = "0.1.0"

// `setup-android-sdk.sh` writes local.properties pointing at .android-sdk/.
// If the operator already has ANDROID_HOME set, fall back to that path so
// CI runners with system-installed SDKs continue to work.
val androidSdkDir: String? =
    providers.environmentVariable("ANDROID_SDK_ROOT").orNull
        ?: providers.environmentVariable("ANDROID_HOME").orNull

if (androidSdkDir != null && file(androidSdkDir).exists()) {
    val localProperties = rootProject.file("local.properties")
    if (!localProperties.exists()) {
        val sdkDirPropertyValue = file(androidSdkDir).absolutePath.replace("\\", "/")
        localProperties.writeText("sdk.dir=$sdkDirPropertyValue")
    }
}

kotlin {
    applyDefaultHierarchyTemplate()

    sourceSets.all {
        languageSettings.optIn("kotlin.time.ExperimentalTime")
        languageSettings.optIn("kotlin.concurrent.atomics.ExperimentalAtomicApi")
    }

    compilerOptions {
        allWarningsAsErrors.set(true)
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    val xcf = XCFramework("LalrpopUtil")

    macosArm64 {
        binaries.framework {
            baseName = "LalrpopUtil"
            xcf.add(this)
        }
    }
    macosX64 {
        binaries.framework {
            baseName = "LalrpopUtil"
            xcf.add(this)
        }
    }
    linuxX64()
    mingwX64()
    iosArm64 {
        binaries.framework {
            baseName = "LalrpopUtil"
            xcf.add(this)
        }
    }
    iosX64 {
        binaries.framework {
            baseName = "LalrpopUtil"
            xcf.add(this)
        }
    }
    iosSimulatorArm64 {
        binaries.framework {
            baseName = "LalrpopUtil"
            xcf.add(this)
        }
    }
    js {
        browser()
        nodejs()
    }
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        nodejs()
    }

    android {
        namespace = "io.github.kotlinmania.lalrpoputil"
        compileSdk = 34
        minSdk = 24
        withHostTestBuilder {}.configure {}
        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                // Intentionally minimal. lalrpop-util-kotlin is the runtime
                // contract every generated parser links against. Adding a
                // dependency here costs every downstream consumer the same
                // dependency. Keep it pure-stdlib unless there is a hard
                // necessity.
            }
        }

        val commonTest by getting { dependencies { implementation(kotlin("test")) } }
    }
    jvmToolchain(21)
}

mavenPublishing {
    publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)
    signAllPublications()

    coordinates(group.toString(), "lalrpop-util-kotlin", version.toString())

    pom {
        name.set("lalrpop-util-kotlin")
        description.set(
            "Kotlin Multiplatform port of the lalrpop-util crate. Runtime " +
                "support for parsers generated by lalrpop-kotlin: ParseError, " +
                "ErrorRecovery, ParserDefinition, and the table-driven LR(1) driver.",
        )
        inceptionYear.set("2026")
        url.set("https://github.com/KotlinMania/lalrpop-util-kotlin")

        licenses {
            license {
                name.set("Apache-2.0")
                url.set("https://opensource.org/licenses/Apache-2.0")
                distribution.set("repo")
            }
            license {
                name.set("MIT")
                url.set("https://opensource.org/licenses/MIT")
                distribution.set("repo")
            }
        }

        developers {
            developer {
                id.set("sydneyrenee")
                name.set("Sydney Renee")
                email.set("sydney@solace.ofharmony.ai")
                url.set("https://github.com/sydneyrenee")
            }
        }

        scm {
            url.set("https://github.com/KotlinMania/lalrpop-util-kotlin")
            connection.set("scm:git:git://github.com/KotlinMania/lalrpop-util-kotlin.git")
            developerConnection.set("scm:git:ssh://github.com/KotlinMania/lalrpop-util-kotlin.git")
        }
    }
}
